name: passing job values

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  pass_in_one_job:
    runs-on: ubuntu-latest
    steps:
      - name: Set color
        id: color-selector
        run: |
          # USTAW ZMIENNĄ
          echo "COLOR=blue" >> $GITHUB_ENV

      - name: Get color
        run: echo "The selected color is $COLOR"

  producer:
    runs-on: ubuntu-latest
    steps:
      - name: Make a sentence
        id: sentence_maker
        run: |
          # USTAW ZMIENNĄ ŚRODOWISKOWĄ
          echo "message=Hello from producer!" >> $GITHUB_OUTPUT
    outputs:
      message: "${{ steps.sentence_maker.outputs.message }}"
          

  consumer:
    runs-on: ubuntu-latest
    needs: producer
    env:
      message: "${{ needs.producer.outputs.message }}"
    steps:
      - name: Print the message
        run: |
          echo "$message"

  job_1:
    name: Add 3 and 7
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        run: |
          expr 3 + 7 > result.txt
          echo "Created result.txt with value:"
          cat result.txt
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: result
          path: result.txt

  job_2:
    name: Multiply by 9
    needs: job_1
    runs-on: windows-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: result

      - shell: bash
        run: |
          value=$(cat result.txt)
          echo $(expr $value \* 9)
