on:
  workflow_dispatch:

env:
  cat_name: "Puszek"

jobs:
  display-variables:
    name: ${{ env.ENVIRONMENT_VAR }}
    runs-on: ubuntu-latest
    env:
      WORKFLOW_VAR: "Jestem zmienną workflow"
      JOB_VAR: "Jestem zmienną joba"
    steps:
      - name: Use variables 1
        env:
          STEP_VAR: "Jestem zmienną stepu"
        run: |
          echo "Repository variable : $REPOSITORY_VAR"
          echo "Organization variable : $ORGANIZATION_VAR"
          echo "Environment variable : $ENVIRONMENT_VAR"
          echo "Ala ma kota o nazwie ${{ env.cat_name }}"
          echo "Powinna być zmienna w scopie workflow: $WORKFLOW_VAR"
          echo "Powinna być zmienna w scopie joba: $JOB_VAR"
          echo "Powinna być zmienna w scopie stepu: $STEP_VAR"

      - name: Use variables 2
        run: |
          echo "Ala ma kota o nazwie ${{ env.cat_name }}"
          echo "Powinna być zmienna w scopie workflow: $WORKFLOW_VAR"
          echo "Powinna być zmienna w scopie joba: $JOB_VAR"
          echo "NIE powinna być zmienna w scopie stepu: $STEP_VAR"

  display-variables2:
    runs-on: ubuntu-latest
    steps:
      - name: Use variables in display-variables2
        run: |
          echo "Powinna być zmienna w scopie workflow: $WORKFLOW_VAR"
          echo "NIE powinna być zmienna w scopie joba: $JOB_VAR"
          echo "NIE powinna być zmienna w scopie stepu: $STEP_VAR"
